FROM quay.io/jupyteronopenshift/s2i-minimal-notebook-py36:2.1.1

USER root

COPY . /tmp/src

RUN rm -rf /tmp/src/.git* && \
    chown -R 1001 /tmp/src && \
    chgrp -R 0 /tmp/src && \
    chmod -R g+w /tmp/src && \
    rm -rf /tmp/scripts && \
    mv /tmp/src/.s2i/bin /tmp/scripts \
    rpm -i http://rpmfind.net/linux/centos/6.10/os/x86_64/Packages/graphviz-2.26.0-10.el6.i686.rpm

ENV XDG_CACHE_HOME=/opt/app-root/src/.cache

USER 1001

RUN /tmp/scripts/assemble

CMD [ "/opt/app-root/builder/run" ]
